### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Distrib-ps** [xfix/PSDevBot#5]
SyntaxError: Unexpected end of JSON input

**Comment by sugar700** [comment]
This likely means the login information (nickname or password) is not correct (although cannot exactly tell if it's precisely that without seeing a backtrace).

**Comment by theodelhay** [comment]
I really search but I do not find here the info


|challstr|4|3dfefd586cc301691acc0db09cf5db38a01c85e3a51e8a050eeb1a8304f8b7d2171faf21585b06a3c72d8394a07116360039bde4916e9e0a3e6b9f1c77936e62218a471d67bcd65fc7f41f43da2f4e399d533257e5b4c871fa6c0d45b0183866eaaf82efa858b0c760057b104aa5298d9574509618aef9bec6749c3f501b9941
undefined:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at EventEmitter.finish (C:\Users\delha\Desktop\PSDevBot-master\showdown.js:115:31)
    at Request.self.callback (C:\Users\delha\Desktop\PSDevBot-master\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\delha\Desktop\PSDevBot-master\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\delha\Desktop\PSDevBot-master\node_modules\request\request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)

and package.json

{
    "name": "psdevbot",
    "version": "0.1.0",
    "description": "Bot that reports changes to Pokemon Showdown on Pokemon Showdown",
    "bugs": "https://github.com/xfix/PSDevBot/issues",
    "license": "MIT",
    "author": "xfix (Konrad Borowski)",
    "repository": {
        "type": "git",
        "url": "https://github.com/xfix/PSDevBot.git"
    },
    "config": {
        "webhookport": "3420",
        "secret": "8cc92258509299f4876ff9180522a851ea508521",
        "server": "91.134.133.245",
        "serverport": "8000",
        "serverid": "pokeland",
        "nickname": "botdedistibtest",
        "password": "",
        "room": "distributions"
    },
    "dependencies": {
        "githubhook": "^1.1.3",
        "python-format": "^1.0.0",
        "websocket": "^1.0.17",
        "request": "^2.53.0",
        "escape-html": "^1.0.1"
    },
    "private": true
}
